return {
	
	VOLUME = 0.1,
	HITSOUND_VOLUME=0.1,
	AFTERCIRCLE_ANIMATION=true,
	--CIRCLES
	EXPERIMENTAL_SPLIT = true,
	APPROACHRATE_ENABLED = true,
	CIRCLESIZE_ENABLED = true,
	SPEEDRATE = 1,
	REACTION = 0.4,
	SCALE = 1.3,
	CIRCLEAPPEAR_TIME = 1,
	EXPONENTIAL_APPROACH_CIRCLE=false,
	APPROACHCIRCLE_SIZE_OFFSET = 0,
	APPROACHCIRCLE = true,
	HITCIRCLE = true,
	HITCIRCLEOVERLAY = true,
	COUNT = true,
	HIDDEN = false,
	HIDDEN_APPROACH_CIRCLE = false,
}
