
return {
	--TEXT
	DEFAULT_FONT="HappyMorin",
	LOADED_FONTS = {"HappyMorin"},
	RESOLUTION_X = 700,
	RESOLUTION_Y = 400,
	NEXT_MAP_SHOW = 5, --MAX=38,MINIMUM=1
	PREVIEW_SONG = true,
	BACKGROUND_TRANSPARENCY = 0.9,
	AVPGS = 0,
	MUSIC_VOLUME = 1.0,
	SHOW_TEXT = true,
}